apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-api

spec:
  replicas: 1

  selector:
    matchLabels:
      app: payments-api
  
  template:
    metadata:
      labels:
        app: payments-api
  
    spec:
      containers:
      - name: payments-api
        image: paymentsapi:latest
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 8070

        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"

        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 8080
        #   periodSeconds: 10
        #   failureThreshold: 3
        #   initialDelaySeconds: 20

        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 8080
        #   periodSeconds: 10
        #   failureThreshold: 5
        #   initialDelaySeconds: 3

        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ASPNETCORE_URLS
          value: http://+:8090
        - name: RabbitMQ__Url
          value: "rabbitmq"
        - name: RabbitMQ__User
          value: "guest"
        - name: RabbitMQ__Password  
          value: "guest"
        - name: RabbitMQ__OrderExchange
          value: "order.exchange"
        - name: RabbitMQ__PaymentExchange
          value: "payment.exchange"
        - name: RabbitMQ__OrderPlacedQueue
          value: "order-placed"
        - name: RabbitMQ__PaymentProcessedQueue
          value: "payment-processed"
        - name: RabbitMQ__OrderPlacedRoutingKey
          value: "order.placed"
        - name: RabbitMQ__PaymentProcessedRoutingKey
          value: "payment.processed"

