apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-api

spec:
  replicas: 1

  selector:
    matchLabels:
      app: payments-api
  
  template:
    metadata:
      labels:
        app: payments-api
  
    spec:
      containers:
      - name: payments-api
        image: fcgpaymentsapi:latest
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 8090

        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"

        envFrom:
        - configMapRef:
            name: configmapcommon            
        - secretRef:
              name: secretfcg

        env:
        - name: ASPNETCORE_URLS
          value: "http://+:8090"

        - name: NEW_RELIC_APP_NAME
          value: "FCG-PaymentsAPI"

        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: newrelic-secret
              key: license-key

        - name: NEW_RELIC_DISTRIBUTED_TRACING_ENABLED
          value: "true"

        - name: NEW_RELIC_APPLICATION_LOGGING_ENABLED
          value: "true"

        - name: NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED
          value: "true"



