apiVersion: v1
kind: ConfigMap
metadata:
  name: notificationapi-config
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  RabbitMQ__UserCreatedQueueName: "user-created"
  RabbitMQ__PaymentProcessedQueueName: "payment-processed"
