apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-api

spec:
  replicas: 1

  selector:
    matchLabels:
      app: notification-api
  
  template:
    metadata:
      labels:
        app: notification-api
  
    spec:
      containers:
      - name: notification-api
        image: notificationapi:latest
        imagePullPolicy: IfNotPresent

        envFrom:
          - configMapRef:
              name: notificationapi-config
          - secretRef:
              name: notificationapi-secret

        ports:
        - containerPort: 5001

        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
            
        env: 
        - name: ASPNETCORE_URLS
          value: "http://+:5001"


        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 8080
        #   periodSeconds: 10
        #   failureThreshold: 3
        #   initialDelaySeconds: 20

        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 8080
        #   periodSeconds: 10
        #   failureThreshold: 5
        #   initialDelaySeconds: 3
