apiVersion: v1
kind: Secret
metadata:
  name: notificationapi-secret
type: Opaque
stringData:
  RabbitMQ__Host: "rabbitmq"
  RabbitMQ__Port: "5672"
  RabbitMQ__Username: "guest"
  RabbitMQ__Password: "guest"
