apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api

spec:
  replicas: 1

  selector:
    matchLabels:
      app: user-api
  
  template:
    metadata:
      labels:
        app: user-api
  
    spec:
      containers:
      - name: user-api
        image: userapi2:latest
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 8070

        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"

        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 8080
        #   periodSeconds: 10
        #   failureThreshold: 3
        #   initialDelaySeconds: 20

        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 8080
        #   periodSeconds: 10
        #   failureThreshold: 5
        #   initialDelaySeconds: 3

        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ASPNETCORE_URLS
          value: http://+:8070
        - name: ConnectionStrings__ConnectionString
          value: "Server=db,1433;Initial Catalog=FiapCloudGames;User Id=sa;Password=Your_strong!Passw0rd;TrustServerCertificate=True;"
        - name: RabbitMQ__Host
          value: "rabbitmq"
        - name: RabbitMQ__Port
          value: "5672"
        - name: RabbitMQ__Username
          value: "guest"
        - name: RabbitMQ__Password  
          value: "guest"
        - name: RabbitMQ__QueueName
          value: "user-created"
        - name: CatalogApi__BaseUrl
          value: "http://catalog-api:8080"
