apiVersion: v1
kind: ConfigMap
metadata:
  name: configmapcommon
data:
  ASPNETCORE_ENVIRONMENT: "Development"

  # RabbitMQ configs comuns
  RabbitMQ__Host: "rabbitmq"
  RabbitMQ__Port: "5672"
  RabbitMQ__Username: "guest"
  RabbitMQ__Password: "guest"

  # Filas específicas
  RabbitMQ__OrderPlacedQueue: "order-placed"
  RabbitMQ__PaymentProcessedQueue: "catalog-payment-processed"
  RabbitMQ__NotificationPaymentProcessedQueue: "notification-payment-processed"
  RabbitMQ__UserCreatedQueue: "user-created"
  CatalogAPI__BaseUrl: "http://catalog-api:8080"


  # Exchanges
  RabbitMQ__OrderExchange: "order.exchange"
  RabbitMQ__PaymentExchange: "payment.exchange"
  RabbitMQ__OrderPlacedRoutingKey: "order.placed"
  RabbitMQ__PaymentProcessedRoutingKey: "payment.processed"
