apiVersion: v1
kind: Secret
metadata:
  name: secretfcg
type: Opaque
stringData:
  ConnectionStrings__ConnectionString: "Server=db,1433;Initial Catalog=FiapCloudGames;User Id=sa;Password=Your_strong!Passw0rd;TrustServerCertificate=True;"
  RabbitMQ__Host: "rabbitmq"
  RabbitMQ__Port: "5672"
  RabbitMQ__Username: "guest"
  RabbitMQ__Password: "guest"
  SA_PASSWORD: Your_strong!Passw0rd