_format_version: "3.0"
_transform: true

services:
  - name: user-api
    url: http://userapi:8070
    routes:
      - name: user-public-routes
        paths:
          - ~/api/User/(CreateUser|Login)$
        methods:
          - POST
        regex_priority: 100
        strip_path: false

      - name: user-swagger-route
        hosts:
          - user.localhost
        paths:
          - /swagger
        strip_path: false

      - name: user-protected-routes
        paths:
          - /api/User
        strip_path: false
        plugins:
          - name: jwt
            config:
              claims_to_verify:
                - exp

  - name: catalog-api
    url: http://catalogapi:80
    routes:
      - name: catalog-swagger-route
        hosts:
          - catalog.localhost
        paths:
          - /swagger
        strip_path: false

      - name: catalog-protected-routes
        paths:
          - /api/Game
          - /api/OnSale
          - /api/UsersGames
        strip_path: false
        plugins:
          - name: jwt
            config:
              claims_to_verify:
                - exp

consumers:
  - username: fcg-app
    custom_id: fcg-client
    jwt_secrets:
      - key: FiapCloudGames
        algorithm: HS256
        secret: '_07P\Wbk|}j:Bp-zC/%`701{Owu?B_dJLSDJaljdlajdlajlda'
